import { useState, useEffect, useCallback, useRef, useMemo } from 'react'
import { useQuery, useMutation } from 'convex/react'
import { api } from '../../../convex/_generated/api'
import TeamPanel from './TeamPanel'
import SoccerField from './SoccerField'
import BalanceIndicator from './BalanceIndicator'
import SuplentesPanel from './SuplentesPanel'
import HinchadaPanel from './HinchadaPanel'
import AssignPlayerModal from './AssignPlayerModal'
import JoinMatchModal from '../player/JoinMatchModal'
import PlayerInfoModal from '../player/PlayerInfoModal'
import PlayerCard from '../player/PlayerCard'
import EmptySlot from '../player/EmptySlot'
import { MAX_SUPLENTES } from '../../utils/constants'
import { generateBalancedTeams, calculateTeamStats, getDefaultPosition, getIdealDistribution } from '../../utils/teamBalancer'

function TeamBuilderStep({ match, onRegisterAddPlayerHandler }) {
  const hasAutoGenerated = useRef(false)
  
  // Modal states
  const [showAssignModal, setShowAssignModal] = useState(false)
  const [showJoinModal, setShowJoinModal] = useState(false)
  const [joinModalPlayerOnly, setJoinModalPlayerOnly] = useState(false)
  const [joinModalType, setJoinModalType] = useState(null)
  const [joinTargetTeam, setJoinTargetTeam] = useState(null) // Track which team the empty slot was clicked on
  const [showPlayerInfo, setShowPlayerInfo] = useState(false)
  const [selectedPlayer, setSelectedPlayer] = useState(null)
  const [selectedRegistration, setSelectedRegistration] = useState(null)
  // Convex queries
  const teamConfigData = useQuery(api.teamConfigurations.getByMatch, { matchId: match._id })
  const registrationsData = useQuery(api.registrations.listByMatch, { matchId: match._id })
  const playersData = useQuery(api.players.list)
  
  // Convex mutations
  const saveTeamConfig = useMutation(api.teamConfigurations.save)
  const getOrCreateTeamConfig = useMutation(api.teamConfigurations.getOrCreate)
  const removeRegistration = useMutation(api.registrations.remove)
  const createRegistration = useMutation(api.registrations.create)
  
  // Convert players array to object for easy lookup
  const players = useMemo(() => {
    if (!playersData) return {}
    return playersData.reduce((acc, player) => {
      acc[player._id] = player
      return acc
    }, {})
  }, [playersData])
  
  // Filter registrations that will attend
  const registrations = useMemo(() => {
    if (!registrationsData) return []
    return registrationsData.filter(r => r.asistira)
  }, [registrationsData])
  
  // Use teamConfig from query or create default
  const [localTeamConfig, setLocalTeamConfig] = useState(null)
  
  const teamConfig = teamConfigData || localTeamConfig
  
  // Reset modal states and auto-generate flag when match changes
  useEffect(() => {
    setShowJoinModal(false)
    setShowAssignModal(false)
    setShowPlayerInfo(false)
    hasAutoGenerated.current = false
    setLocalTeamConfig(null)
  }, [match._id])
  
  // Initialize team config if it doesn't exist
  useEffect(() => {
    const initConfig = async () => {
      if (teamConfigData === null && !localTeamConfig) {
        const config = await getOrCreateTeamConfig({ matchId: match._id })
        setLocalTeamConfig(config)
      }
    }
    initConfig()
  }, [teamConfigData, localTeamConfig, getOrCreateTeamConfig, match._id])
  
  // Auto-generate teams on first load if no assignments exist
  useEffect(() => {
    const autoGenerate = async () => {
      if (!teamConfig || !registrations.length || !Object.keys(players).length) return
      
      // Filter only jugadores (not suplentes or hinchada) - also include undefined/null tipoInscripcion as jugador
      const jugadorRegs = registrations.filter(r => 
        r.tipoInscripcion === 'jugador' || r.tipoInscripcion === undefined || r.tipoInscripcion === null
      )
      
      // Only auto-generate if there are no existing assignments and we have players
      if (!hasAutoGenerated.current && teamConfig.asignaciones.length === 0 && jugadorRegs.length > 0) {
        const playerList = jugadorRegs.map(r => players[r.jugadorId]).filter(Boolean)
        if (playerList.length > 0) {
          try {
            const assignments = generateBalancedTeams(playerList, jugadorRegs, match.jugadoresPorEquipo)
            
            await saveTeamConfig({
              partidoId: match._id,
              asignaciones: assignments
            })
            // Only mark as generated after successful save
            hasAutoGenerated.current = true
          } catch (err) {
            console.error('Error auto-generating teams:', err)
            // Don't mark as generated so it can retry
          }
        }
      }
    }
    autoGenerate()
  }, [teamConfig, registrations, players, match.jugadoresPorEquipo, match._id, saveTeamConfig])
  
  // Get assignment for a player
  const getAssignment = (playerId) => {
    return teamConfig?.asignaciones?.find(a => a.jugadorId === playerId)
  }
  
  // Handle team name change
  const handleTeamNameChange = async (team, newName) => {
    await saveTeamConfig({
      partidoId: match._id,
      [team === 'blanco' ? 'nombreEquipoBlanco' : 'nombreEquipoOscuro']: newName
    })
  }
  
  // Handle player assignment
  const handleAssignPlayer = async (playerId, team, role) => {
    const existingAssignments = teamConfig.asignaciones.filter(a => a.jugadorId !== playerId)
    
    // Calculate position based on role and existing players
    const teamAssignments = existingAssignments.filter(a => a.equipo === team)
    const roleCount = teamAssignments.filter(a => a.rol === role).length
    
    const totalInRole = getIdealDistribution(match.jugadoresPorEquipo)[role] || roleCount + 1
    const position = getDefaultPosition(role, team, roleCount, totalInRole)

    const newAssignment = {
      jugadorId: playerId,
      equipo: team,
      rol: role,
      coordenadaX: position.x,
      coordenadaY: position.y
    }

    await saveTeamConfig({
      partidoId: match._id,
      asignaciones: [...existingAssignments, newAssignment]
    })

    setShowAssignModal(false)
    setSelectedPlayer(null)
  }
  
  // Handle removing player from team
  const handleUnassignPlayer = async (playerId) => {
    // Remove player from assignments
    const newAssignments = teamConfig.asignaciones.filter(a => a.jugadorId !== playerId)
    
    // Remove player's registration from the match entirely
    await removeRegistration({ matchId: match._id, playerId })
    
    await saveTeamConfig({
      partidoId: match._id,
      asignaciones: newAssignments
    })
  }
  
  // Handle promoting a suplente manually
  const handlePromoteSuplente = async (playerId, targetTeamOverride = null) => {
    const suplenteReg = registrations.find(r => r.jugadorId === playerId && r.tipoInscripcion === 'suplente')
    if (!suplenteReg) return
    
    // Promote to jugador (update registration)
    await createRegistration({
      partidoId: match._id,
      jugadorId: playerId,
      estadoFisico: suplenteReg.estadoFisico,
      confirmado: true,
      asistira: true
    })
    
    // Use override team or assign to team with fewer players
    let targetTeam = targetTeamOverride
    if (!targetTeam) {
      const blancoCount = teamConfig.asignaciones.filter(a => a.equipo === 'blanco').length
      const oscuroCount = teamConfig.asignaciones.filter(a => a.equipo === 'oscuro').length
      targetTeam = blancoCount <= oscuroCount ? 'blanco' : 'oscuro'
    }
    
    const player = players[playerId]
    const preferredPosition = player?.perfilPermanente?.posicionPreferida || 'Mediocampista'
    const roleMap = {
      'Arquero': 'arquero',
      'Defensor': 'defensor',
      'Mediocampista': 'medio',
      'Delantero': 'delantero'
    }
    const role = roleMap[preferredPosition] || 'medio'
    
    const teamAssignments = teamConfig.asignaciones.filter(a => a.equipo === targetTeam)
    const roleCount = teamAssignments.filter(a => a.rol === role).length
    const totalInRole = getIdealDistribution(match.jugadoresPorEquipo)[role] || roleCount + 1
    const position = getDefaultPosition(role, targetTeam, roleCount, totalInRole)
    
    const newAssignment = {
      jugadorId: playerId,
      equipo: targetTeam,
      rol: role,
      coordenadaX: position.x,
      coordenadaY: position.y
    }
    
    await saveTeamConfig({
      partidoId: match._id,
      asignaciones: [...teamConfig.asignaciones, newAssignment]
    })
  }
  
  // Handle player position change (drag & drop)
  const handlePositionChange = async (playerId, x, y) => {
    const updatedAssignments = teamConfig.asignaciones.map(a => {
      if (a.jugadorId === playerId) {
        return { ...a, coordenadaX: x, coordenadaY: y }
      }
      return a
    })
    
    await saveTeamConfig({
      partidoId: match._id,
      asignaciones: updatedAssignments
    })
  }
  
  // Handle swapping a player to the other team
  const handleSwapTeam = async (playerId) => {
    const assignment = teamConfig.asignaciones.find(a => a.jugadorId === playerId)
    if (!assignment) return
    
    const newTeam = assignment.equipo === 'blanco' ? 'oscuro' : 'blanco'
    // Field is landscape: mirror X position to the other half
    const newX = 100 - assignment.coordenadaX

    const updatedAssignments = teamConfig.asignaciones.map(a =>
      a.jugadorId === playerId
        ? { ...a, equipo: newTeam, coordenadaX: newX }
        : a
    )
    
    await saveTeamConfig({
      partidoId: match._id,
      asignaciones: updatedAssignments
    })
  }
  
  // Open assign modal for a player
  const handleOpenAssign = (player) => {
    const playerId = player._id || player.id
    const reg = registrations.find(r => r.jugadorId === playerId)
    setSelectedPlayer(player)
    setSelectedRegistration(reg)
    setShowAssignModal(true)
  }
  
  // Open player info modal
  const handleViewPlayerInfo = (player) => {
    const playerId = player._id || player.id
    const reg = registrations.find(r => r.jugadorId === playerId)
    setSelectedPlayer(player)
    setSelectedRegistration(reg)
    setShowPlayerInfo(true)
  }
  
  // Handle new player joined - auto-assign to target team if specified
  const handlePlayerJoined = async (newPlayerId) => {
    // If we have a target team from clicking an empty slot, auto-assign the player
    if (joinTargetTeam && newPlayerId && teamConfig) {
      // Try to get player info from cache, but don't depend on it
      const newPlayer = players[newPlayerId]
      
      // Get role - use player preference if available, otherwise default to 'medio'
      let role = 'medio'
      if (newPlayer?.perfilPermanente?.posicionPreferida) {
        const roleMap = {
          'Arquero': 'arquero',
          'Defensor': 'defensor',
          'Mediocampista': 'medio',
          'Delantero': 'delantero'
        }
        role = roleMap[newPlayer.perfilPermanente.posicionPreferida] || 'medio'
      }
      
      // Calculate position
      const teamAssignments = teamConfig.asignaciones.filter(a => a.equipo === joinTargetTeam)
      const roleCount = teamAssignments.filter(a => a.rol === role).length
      const totalInRole = getIdealDistribution(match.jugadoresPorEquipo)[role] || roleCount + 1
      const position = getDefaultPosition(role, joinTargetTeam, roleCount, totalInRole)
      
      const newAssignment = {
        jugadorId: newPlayerId,
        equipo: joinTargetTeam,
        rol: role,
        coordenadaX: position.x,
        coordenadaY: position.y
      }
      
      try {
        await saveTeamConfig({
          partidoId: match._id,
          asignaciones: [...teamConfig.asignaciones, newAssignment]
        })
      } catch (err) {
        console.error('Error assigning player to team:', err)
      }
    }
    
    // Reset target team
    setJoinTargetTeam(null)
    
    // Data will auto-refresh via Convex
  }
  
  // Open join modal for empty slot (player only) - receives target team
  const handleOpenJoinFromEmptySlot = useCallback((targetTeam) => {
    setJoinTargetTeam(targetTeam)
    setJoinModalPlayerOnly(true)
    setShowJoinModal(true)
  }, [])

  // Open join modal from header (all options)
  const handleOpenJoinFromHeader = useCallback(() => {
    setJoinModalPlayerOnly(false)
    setJoinModalType(null)
    setShowJoinModal(true)
  }, [])

  // Open join modal pre-selecting a registration type (suplente / hinchada)
  const openJoinWithType = useCallback((type) => {
    setJoinModalPlayerOnly(false)
    setJoinTargetTeam(null)
    setJoinModalType(type)
    setShowJoinModal(true)
  }, [])

  const handleRemoveExtraPlayer = useCallback(async (player) => {
    try {
      await removeRegistration({ matchId: match._id, playerId: player._id })
    } catch (err) {
      console.error('Error removing registration:', err)
    }
  }, [match._id, removeRegistration])

  // Register the add player handler for the header button
  useEffect(() => {
    if (onRegisterAddPlayerHandler) {
      onRegisterAddPlayerHandler(() => handleOpenJoinFromHeader())
    }
    
    // Cleanup: unregister handler when component unmounts
    return () => {
      if (onRegisterAddPlayerHandler) {
        onRegisterAddPlayerHandler(null)
      }
    }
  }, [onRegisterAddPlayerHandler, handleOpenJoinFromHeader])
  
  // Calculate team stats
  const teamStats = teamConfig ? calculateTeamStats(teamConfig.asignaciones, players, registrations) : null
  
  // Get suplentes and hinchada
  const suplentes = registrations.filter(r => r.tipoInscripcion === 'suplente')
  const hinchada = registrations.filter(r => r.tipoInscripcion === 'hinchada')
  
  // Get assigned players by team
  const blancoPlayers = teamConfig?.asignaciones
    ?.filter(a => a.equipo === 'blanco')
    .map(a => ({ ...a, player: players[a.jugadorId] }))
    .filter(a => a.player) || []
    
  const oscuroPlayers = teamConfig?.asignaciones
    ?.filter(a => a.equipo === 'oscuro')
    .map(a => ({ ...a, player: players[a.jugadorId] }))
    .filter(a => a.player) || []
  
  if (!teamConfig) {
    return <div className="loading">Cargando...</div>
  }
  
  const sortedSuplentes = [...suplentes].sort((a, b) => new Date(a.timestamp) - new Date(b.timestamp))
  const sortedHinchada = [...hinchada].sort((a, b) => new Date(a.timestamp) - new Date(b.timestamp))

  const teamsHaveEmptySlots =
    blancoPlayers.length < match.jugadoresPorEquipo ||
    oscuroPlayers.length < match.jugadoresPorEquipo
  const promoteSuplente = (player) => handlePromoteSuplente(player._id)

  return (
    <>
    <SoccerField
      teamConfig={teamConfig}
      players={players}
      registrations={registrations}
      onPositionChange={handlePositionChange}
      onSwapTeam={handleSwapTeam}
      onPlayerClick={handleViewPlayerInfo}
    />
    <div className="team-builder-step">
      <div className="team-builder-layout-new">
        <div className="team-builder-teams-row">
          <TeamPanel
            team="blanco"
            teamName={teamConfig.nombreEquipoBlanco}
            players={blancoPlayers}
            registrations={registrations}
            onViewInfo={handleViewPlayerInfo}
            onUnassign={handleUnassignPlayer}
            onSwapTeam={handleSwapTeam}
            onAddPlayer={handleOpenJoinFromEmptySlot}
            onTeamNameChange={handleTeamNameChange}
            jugadoresPorEquipo={match.jugadoresPorEquipo}
          />
          <TeamPanel
            team="oscuro"
            teamName={teamConfig.nombreEquipoOscuro}
            players={oscuroPlayers}
            registrations={registrations}
            onViewInfo={handleViewPlayerInfo}
            onUnassign={handleUnassignPlayer}
            onSwapTeam={handleSwapTeam}
            onAddPlayer={handleOpenJoinFromEmptySlot}
            onTeamNameChange={handleTeamNameChange}
            jugadoresPorEquipo={match.jugadoresPorEquipo}
          />
        </div>

        {teamStats && (
          <BalanceIndicator
            teamStats={teamStats}
            teamConfig={teamConfig}
          />
        )}
      </div>
      
      {/* Modals */}
      <AssignPlayerModal
        isOpen={showAssignModal}
        onClose={() => {
          setShowAssignModal(false)
          setSelectedPlayer(null)
        }}
        player={selectedPlayer}
        registration={selectedRegistration}
        currentAssignment={selectedPlayer ? getAssignment(selectedPlayer._id || selectedPlayer.id) : null}
        teamConfig={teamConfig}
        playersPerTeam={match.jugadoresPorEquipo}
        onAssign={handleAssignPlayer}
        onUnassign={handleUnassignPlayer}
      />
      
      <JoinMatchModal
        isOpen={showJoinModal}
        onClose={() => setShowJoinModal(false)}
        matchId={match._id}
        match={match}
        onJoined={handlePlayerJoined}
        playerOnly={joinModalPlayerOnly}
        defaultType={joinModalType}
      />
      
      <PlayerInfoModal
        isOpen={showPlayerInfo}
        onClose={() => {
          setShowPlayerInfo(false)
          setSelectedPlayer(null)
        }}
        player={selectedPlayer}
        registration={selectedRegistration}
        assignment={selectedPlayer ? getAssignment(selectedPlayer._id || selectedPlayer.id) : null}
        onSwapTeam={handleSwapTeam}
      />

    </div>

    <div className="team-builder-extras-row">
      <div className="inscription-step">
        <div className="inscription-step-header">
          <p className="step-title">
            <img src="/icons/moveplayer.svg" alt="" className="step-title-icon" width="24" height="24" />
            Suplentes
          </p>
        </div>
        <div className="player-list compact-list">
          {sortedSuplentes.map((registration, index) => {
            const player = players[registration.jugadorId]
            if (!player) return null
            return (
              <PlayerCard
                key={registration.jugadorId}
                player={player}
                registration={registration}
                onRemove={handleRemoveExtraPlayer}
                onMove={teamsHaveEmptySlots ? promoteSuplente : undefined}
                index={index}
                compact={true}
              />
            )
          })}
          {sortedSuplentes.length < MAX_SUPLENTES && (
            <EmptySlot index={sortedSuplentes.length} onClick={() => openJoinWithType('suplente')} />
          )}
        </div>
      </div>

      <div className="inscription-step">
        <div className="inscription-step-header">
          <p className="step-title">
            <img src="/icons/hinchada.svg" alt="" className="step-title-icon" width="24" height="24" />
            Hinchada
          </p>
        </div>
        <div className="player-list compact-list">
          {sortedHinchada.map((registration, index) => {
            const player = players[registration.jugadorId]
            if (!player) return null
            return (
              <PlayerCard
                key={registration.jugadorId}
                player={player}
                registration={registration}
                onRemove={handleRemoveExtraPlayer}
                index={index}
                compact={true}
                showState={false}
              />
            )
          })}
          <EmptySlot index={sortedHinchada.length} onClick={() => openJoinWithType('hinchada')} />
        </div>
      </div>
    </div>
    </>
  )
}

export default TeamBuilderStep
